package com.kingzulu.biblepresentation

data class BibleReference(val book:String,val chapter:Int,val verseStart:Int?=null,val verseEnd:Int?=null){fun display()=buildString{append("$book $chapter");verseStart?.let{append(":$it");if(verseEnd!=null&&verseEnd!=it)append("–$verseEnd")}}}
object BibleReferenceParser{
 private val aliases=mutableMapOf<String,String>().apply{fun add(book:String,vararg names:String){(listOf(book)+names).forEach{put(it.lowercase(),book)}}
 add("Genesis","gen","ge","gn");add("Exodus","ex","exo","exod");add("Leviticus","lev","lv","levit");add("Numbers","num","nu","nm","numb");add("Deuteronomy","deut","dt","deu");add("Joshua","josh","jos","jsh");add("Judges","judg","jdg","jgs");add("Ruth","ru","rth");add("1 Samuel","1 sam","1sam","1 sa","1sa","first samuel");add("2 Samuel","2 sam","2sam","2 sa","2sa","second samuel");add("1 Kings","1 kgs","1kgs","1 ki","1ki","1 king","first kings");add("2 Kings","2 kgs","2kgs","2 ki","2ki","2 king","second kings");add("1 Chronicles","1 chr","1chr","1 ch","1ch","first chronicles");add("2 Chronicles","2 chr","2chr","2 ch","2ch","second chronicles");add("Ezra","ezr");add("Nehemiah","neh","ne");add("Esther","est","esth");add("Job","jb");add("Psalms","psalm","ps","psa","psm");add("Proverbs","prov","pr","prv","pro");add("Ecclesiastes","eccl","ecc","ec","ecl");add("Song of Solomon","song","songs","sos","song of songs","ss");add("Isaiah","isa","is");add("Jeremiah","jer","je","jr");add("Lamentations","lam","la");add("Ezekiel","ezek","eze","ezk");add("Daniel","dan","dn");add("Hosea","hos","ho");add("Joel","jl");add("Amos","am");add("Obadiah","obad","ob");add("Jonah","jon");add("Micah","mic","mi");add("Nahum","nah","na");add("Habakkuk","hab");add("Zephaniah","zeph","zep");add("Haggai","hag");add("Zechariah","zech","zec");add("Malachi","mal");add("Matthew","matt","mt","mat");add("Mark","mk","mrk","mar");add("Luke","lk","luk");add("John","jn","jhn","joh");add("Acts","act","ac");add("Romans","rom","ro","rm");add("1 Corinthians","1 cor","1cor","1 co","1co","first corinthians");add("2 Corinthians","2 cor","2cor","2 co","2co","second corinthians");add("Galatians","gal","ga");add("Ephesians","eph","ep");add("Philippians","phil","php","phlp","phi");add("Colossians","col","coloss");add("1 Thessalonians","1 thess","1thess","1 thes","1thes","1 th","1th","first thessalonians");add("2 Thessalonians","2 thess","2thess","2 thes","2thes","2 th","2th","second thessalonians");add("1 Timothy","1 tim","1tim","1 ti","1ti","first timothy");add("2 Timothy","2 tim","2tim","2 ti","2ti","second timothy");add("Titus","tit");add("Philemon","philem","phm","phile");add("Hebrews","heb","hebr");add("James","jas","jam","jm");add("1 Peter","1 pet","1pet","1 pe","1pe","1 ptr","first peter");add("2 Peter","2 pet","2pet","2 pe","2pe","2 ptr","second peter");add("1 John","1 jn","1jn","1 john","1john","first john");add("2 John","2 jn","2jn","2 john","2john","second john");add("3 John","3 jn","3jn","3 john","3john","third john");add("Jude","jud");add("Revelation","rev","rv","re","revelations","revel")}
 private val units=mapOf("zero" to 0,"one" to 1,"two" to 2,"three" to 3,"four" to 4,"five" to 5,"six" to 6,"seven" to 7,"eight" to 8,"nine" to 9,"ten" to 10,"eleven" to 11,"twelve" to 12,"thirteen" to 13,"fourteen" to 14,"fifteen" to 15,"sixteen" to 16,"seventeen" to 17,"eighteen" to 18,"nineteen" to 19)
 private val tens=mapOf("twenty" to 20,"thirty" to 30,"forty" to 40,"fifty" to 50,"sixty" to 60,"seventy" to 70,"eighty" to 80,"ninety" to 90)
 private fun spokenNumbers(input:String):String{val words=input.lowercase().replace('-', ' ').split(Regex("\\s+")).filter{it.isNotBlank()};val out=mutableListOf<String>();var i=0;while(i<words.size){val w=words[i];if(w in units||w in tens){var n=0;if(w in units)n=units.getValue(w) else{n=tens.getValue(w);if(i+1<words.size&&words[i+1] in units){n+=units.getValue(words[i+1]);i++}};if(i+1<words.size&&words[i+1]=="hundred"){n*=100;i++;if(i+1<words.size&&words[i+1]=="and")i++;if(i+1<words.size&&(words[i+1] in units||words[i+1] in tens)){val next=words[++i];n+=units[next]?:tens[next]?:0;if(next in tens&&i+1<words.size&&words[i+1] in units)n+=units.getValue(words[++i])}};out+=n.toString()}else out+=w;i++};return out.joinToString(" ")}
 fun suggestions(input:String,limit:Int=5):List<String>{val raw=spokenNumbers(input).trim();if(raw.isBlank())return emptyList();val bookPart=raw.replace(Regex("\\s+\\d.*$"),"").trim();return aliases.entries.filter{(alias,book)->alias.startsWith(bookPart)||book.lowercase().startsWith(bookPart)}.sortedWith(compareBy<Map.Entry<String,String>>{if(it.key==bookPart)0 else 1}.thenBy{it.key.length}).map{it.value}.distinct().take(limit)}
 fun parse(input:String):BibleReference?{var s=spokenNumbers(input).replace(Regex("\\bchapter\\b")," ").replace(Regex("\\bverses?\\b")," ").replace(Regex("\\bvs?\\.?\\b")," ").replace(":"," ").replace(","," ").replace(Regex("([a-z])(\\d)"),"$1 $2").replace(Regex("(\\d)([a-z])"),"$1 $2").replace(Regex("\\s+")," ").trim();val m=Regex("^(.+?)\\s+(\\d+)(?:\\s+(\\d+)(?:\\s*(?:-|–|to|through)\\s*(\\d+))?)?$",RegexOption.IGNORE_CASE).matchEntire(s)?:return null;val book=aliases[m.groupValues[1].trim().replace(Regex("\\s+")," ")]?:return null;val chapter=m.groupValues[2].toIntOrNull()?:return null;val start=m.groupValues[3].takeIf{it.isNotBlank()}?.toIntOrNull();val end=m.groupValues[4].takeIf{it.isNotBlank()}?.toIntOrNull();return BibleReference(book,chapter,start,end)}
}
