package com.kingzulu.biblepresentation
import android.content.Context
import android.net.wifi.WifiManager
import java.io.*
import java.net.*
import java.util.Collections
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicBoolean
import org.json.JSONObject
class BrowserReceiverServer(private val context:Context){private val running=AtomicBoolean(false);private val pool=Executors.newCachedThreadPool();private var server:ServerSocket?=null;@Volatile private var snapshot=ReceiverSnapshot()
data class ReceiverSnapshot(val reference:String="",val text:String="",val translation:String="",val kind:String="",val black:Boolean=false,val background:String="",val overlay:Float=.38f,val textSize:Int=32,val autoFit:Boolean=true,val revision:Long=0)
fun start(port:Int=8787):String?{if(running.get())return address(port);return runCatching{server=ServerSocket(port).also{ss->running.set(true);pool.execute{while(running.get())runCatching{ss.accept()}.getOrNull()?.let{c->pool.execute{serve(c)}}}};address(port)}.getOrNull()}
fun publish(slide:PresentationSlide?,black:Boolean,theme:BackgroundTheme?=null,textSize:Int=32,autoFit:Boolean=true){snapshot=ReceiverSnapshot(slide?.reference.orEmpty(),slide?.text.orEmpty(),slide?.translation.orEmpty(),slide?.kind.orEmpty(),black,theme?.localPath.orEmpty(),theme?.overlay?:.38f,textSize,autoFit,snapshot.revision+1)}
fun stop(){running.set(false);runCatching{server?.close()};server=null}
private fun serve(socket:Socket)=socket.use{s->s.soTimeout=2500;val reader=BufferedReader(InputStreamReader(s.getInputStream()));val first=reader.readLine().orEmpty();var line:String?;do{line=reader.readLine()}while(!line.isNullOrEmpty());val raw=first.split(' ').getOrNull(1)?:"/";val path=URLDecoder.decode(raw.substringBefore('?'),"UTF-8");if(path=="/background"){val f=File(snapshot.background);if(f.exists()){val bytes=f.readBytes();write(s,"image/jpeg",bytes);return@use}};val body=if(path=="/state")stateJson() else receiverHtml();write(s,if(path=="/state")"application/json; charset=utf-8" else "text/html; charset=utf-8",body.toByteArray())}
private fun write(s:Socket,type:String,bytes:ByteArray){val out=s.getOutputStream();out.write("HTTP/1.1 200 OK\r\nContent-Type: $type\r\nContent-Length: ${bytes.size}\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n".toByteArray());out.write(bytes);out.flush()}
private fun stateJson()=snapshot.let{s->JSONObject().apply{put("reference",s.reference);put("text",s.text);put("translation",s.translation);put("kind",s.kind);put("black",s.black);put("hasBackground",s.background.isNotBlank()&&File(s.background).exists());put("overlay",s.overlay);put("textSize",s.textSize);put("autoFit",s.autoFit);put("revision",s.revision)}.toString()}
private fun receiverHtml()="""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000;color:#fff;font-family:Arial,sans-serif}#bg,#shade,#stage{position:fixed;inset:0}#bg{background-size:cover;background-position:center}#stage{box-sizing:border-box;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:5vh 6vw}.ref{font-size:2.5vw;font-weight:700;margin-bottom:2vh}.body{line-height:1.16;font-weight:600;max-width:92vw;white-space:pre-wrap}.tr{font-size:1.7vw;margin-top:2vh}.hint{font-size:2vw;color:#888}</style></head><body><div id='bg'></div><div id='shade'></div><div id='stage'><div class='hint'>KING ZULU RECEIVER</div></div><script>let rev=-1,w=null;async function awake(){try{if('wakeLock'in navigator&&!w){w=await navigator.wakeLock.request('screen');w.onrelease=()=>w=null}}catch(e){}}function fit(el,want,auto){let px=want*innerWidth/1000;el.style.fontSize=px+'px';if(!auto)return;let min=Math.max(16,innerHeight*.025);while((el.scrollHeight>innerHeight*.72||el.scrollWidth>innerWidth*.9)&&px>min){px-=1;el.style.fontSize=px+'px'}}async function tick(){try{let s=await(await fetch('/state?'+Date.now(),{cache:'no-store'})).json();if(s.revision===rev)return;rev=s.revision;awake();let st=document.getElementById('stage'),bg=document.getElementById('bg'),sh=document.getElementById('shade');if(s.black){st.innerHTML='';bg.style.backgroundImage='none';sh.style.background='#000';return}bg.style.backgroundImage=s.hasBackground?'url(/background?r='+s.revision+')':'none';sh.style.background='rgba(0,0,0,'+(s.hasBackground?s.overlay:1)+')';if(!s.text&&!s.reference){st.innerHTML='<div class=hint>Ready</div>';return}st.innerHTML='<div class=ref></div><div class=body></div><div class=tr></div>';st.querySelector('.ref').textContent=s.reference||'';let b=st.querySelector('.body');b.textContent=s.text||'';st.querySelector('.tr').textContent=s.translation||'';fit(b,s.textSize,s.autoFit)}catch(e){}}document.addEventListener('visibilitychange',awake);document.addEventListener('click',awake);awake();setInterval(tick,300);tick()</script></body></html>"""
private fun address(port:Int)=localIpv4()?.let{"http://$it:$port"};private fun localIpv4():String?{val interfaces=Collections.list(NetworkInterface.getNetworkInterfaces());return interfaces.asSequence().flatMap{Collections.list(it.inetAddresses).asSequence()}.filterIsInstance<Inet4Address>().firstOrNull{!it.isLoopbackAddress&&it.isSiteLocalAddress}?.hostAddress?:runCatching{val wifi=context.applicationContext.getSystemService(Context.WIFI_SERVICE)as WifiManager;val ip=wifi.connectionInfo.ipAddress;if(ip==0)null else "%d.%d.%d.%d".format(ip and 255,ip shr 8 and 255,ip shr 16 and 255,ip shr 24 and 255)}.getOrNull()}}
