package com.kingzulu.biblepresentation

import android.app.Activity
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.mediarouter.media.MediaRouter
import com.google.android.gms.cast.framework.CastContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

private val DS=Color(0xFF151518);private val DM=Color(0xFFAAAAB2);private val DG=Color(0xFF66D19E)

@Composable private fun RouteSelector(transport:OutputTransport,onChanged:()->Unit={}){var selected by remember{mutableStateOf(OutputRouting.busFor(transport))};Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("ROUTE TO",fontSize=11.sp,color=DM,fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){PresentationBus.entries.forEach{bus->if(selected==bus)Button({OutputRouting.assign(transport,bus);selected=bus;onChanged()},Modifier.weight(1f)){Text(if(bus==PresentationBus.MAIN)"MAIN" else "FOLDBACK")}else OutlinedButton({OutputRouting.assign(transport,bus);selected=bus;onChanged()},Modifier.weight(1f)){Text(if(bus==PresentationBus.MAIN)"MAIN" else "FOLDBACK")}}};Text(if(selected==PresentationBus.MAIN)"Congregation / audience feed" else "Stage foldback · current + next scripture · clock/timer/alerts",fontSize=11.sp,color=DM)}}

@Composable fun DisplaysPanel(sharedWiredBridge:WiredDisplayBridge?=null,browserReceiver:BrowserReceiverServer?=null){
 val context=LocalContext.current;val activity=context as? Activity;val scope=rememberCoroutineScope();val discovery=remember{KingZuluDisplayDiscovery(context)};val castBridge=remember{GoogleCastBridge(context)};val wired=sharedWiredBridge?:remember{WiredDisplayBridge(context)};val browser=browserReceiver?:remember{BrowserReceiverServer(context)}
 val mediaRouter=remember{MediaRouter.getInstance(context)};var castSearching by remember{mutableStateOf(false)};val castRoutes=remember{mutableStateListOf<MediaRouter.RouteInfo>()};var castMessage by remember{mutableStateOf("Chromecast, Google TV and compatible Cast TVs")};var browserRunning by remember{mutableStateOf(browser.isRunning())};var castDevice by remember{mutableStateOf(castBridge.currentDeviceName())};var browserClients by remember{mutableIntStateOf(browser.connectedClients())};var mainBrowserClients by remember{mutableIntStateOf(browser.connectedMainClients())};var foldbackBrowserClients by remember{mutableIntStateOf(browser.connectedFoldbackClients())};var castActive by remember{mutableStateOf(castBridge.hasActiveSession())};var wiredActive by remember{mutableStateOf(wired.isActive())};var routeRevision by remember{mutableIntStateOf(0)};var diagnostics by remember{mutableStateOf(false)};var foldbackControls by remember{mutableStateOf(false)};var scanning by remember{mutableStateOf(false)};var smartScanning by remember{mutableStateOf(false)};var smartMessage by remember{mutableStateOf("VIDAA, Hisense and compatible DLNA TVs")};val devices=remember{mutableStateListOf<DiscoveredDisplay>()};val smartTvs=remember{mutableStateListOf<Pair<SmartTvRenderer,String>>()}
 LaunchedEffect(Unit){FoldbackWidgetState.initialize(context);while(true){castDevice=castBridge.currentDeviceName();castActive=castBridge.hasActiveSession();wiredActive=wired.isActive();browserRunning=browser.isRunning();browserClients=browser.connectedClients();mainBrowserClients=browser.connectedMainClients();foldbackBrowserClients=browser.connectedFoldbackClients();delay(1000)}}
 DisposableEffect(mediaRouter){val selector=CastContext.getSharedInstance(context).mergedSelector;val cb=object:MediaRouter.Callback(){override fun onRouteAdded(router:MediaRouter,route:MediaRouter.RouteInfo){if(selector!=null&&route.matchesSelector(selector)&&!route.isDefault&&castRoutes.none{it.id==route.id})castRoutes.add(route)};override fun onRouteRemoved(router:MediaRouter,route:MediaRouter.RouteInfo){castRoutes.removeAll{it.id==route.id}};override fun onRouteChanged(router:MediaRouter,route:MediaRouter.RouteInfo){if(selector!=null&&route.matchesSelector(selector)&&!route.isDefault){castRoutes.removeAll{it.id==route.id};castRoutes.add(route)}}};if(selector!=null){mediaRouter.routes.filter{it.matchesSelector(selector)&&!it.isDefault}.forEach{if(castRoutes.none{r->r.id==it.id})castRoutes.add(it)};mediaRouter.addCallback(selector,cb,MediaRouter.CALLBACK_FLAG_REQUEST_DISCOVERY);castSearching=true;castMessage="Searching for Cast TVs…"}else castMessage="Cast is unavailable on this device.";onDispose{mediaRouter.removeCallback(cb)}}
 LaunchedEffect(castSearching){if(castSearching){val selector=CastContext.getSharedInstance(context).mergedSelector ?: run { castSearching=false;castMessage="Cast is unavailable on this device.";return@LaunchedEffect };castRoutes.clear();mediaRouter.routes.filter{it.matchesSelector(selector)&&!it.isDefault}.forEach{castRoutes.add(it)};val cb=object:MediaRouter.Callback(){override fun onRouteAdded(router:MediaRouter,route:MediaRouter.RouteInfo){if(route.matchesSelector(selector)&&!route.isDefault&&castRoutes.none{it.id==route.id})castRoutes.add(route)}};mediaRouter.addCallback(selector,cb,MediaRouter.CALLBACK_FLAG_REQUEST_DISCOVERY);delay(12000);mediaRouter.removeCallback(cb);castSearching=false;castMessage=if(castRoutes.isEmpty())"No Cast TVs found yet. Discovery remains active; use FIND CAST TVs to refresh." else "${castRoutes.size} Cast device${if(castRoutes.size==1)"" else "s"} found"}}
 LaunchedEffect(scanning){if(scanning){delay(3500);discovery.stop();scanning=false}}
 fun connectCastRoute(route:MediaRouter.RouteInfo){castMessage="Connecting to ${route.name}…";runCatching{mediaRouter.selectRoute(route)}.onFailure{castMessage="Could not start Cast connection. Tap FIND CAST TVs and try again."}}
 fun scan(){devices.clear();scanning=true;discovery.start{d->if(devices.none{it.host==d.host&&it.port==d.port})devices.add(d)}}
 fun scanSmartTvs(){if(smartScanning)return;smartScanning=true;smartTvs.clear();smartMessage="Searching your local network…";scope.launch{val found=withContext(Dispatchers.IO){DlnaDiscovery.scan()};found.forEach{r->val name=withContext(Dispatchers.IO){DlnaDiscovery.friendlyName(r)};smartTvs.add(r to name)};smartMessage=if(found.isEmpty())"No compatible Smart TVs found" else "${found.size} compatible Smart TV${if(found.size==1)"" else "s"} found";smartScanning=false}}
 DisposableEffect(Unit){onDispose{discovery.stop();if(browserReceiver==null)browser.stop();if(sharedWiredBridge==null)wired.dismiss()}}
 val ignored=routeRevision;val castBus=OutputRouting.busFor(OutputTransport.CAST);val wiredBus=OutputRouting.busFor(OutputTransport.WIRED);val mainCount=mainBrowserClients+(if(castActive&&castBus==PresentationBus.MAIN)1 else 0)+(if(wiredActive&&wiredBus==PresentationBus.MAIN)1 else 0);val foldbackCount=foldbackBrowserClients+(if(castActive&&castBus==PresentationBus.FOLDBACK)1 else 0)+(if(wiredActive&&wiredBus==PresentationBus.FOLDBACK)1 else 0);val totalCount=mainCount+foldbackCount
 Text("Outputs",fontSize=32.sp,fontWeight=FontWeight.Black);Text("Connect displays, then choose what each output receives.",color=DM)
 Card{Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("LIVE OUTPUTS",fontWeight=FontWeight.Black);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("MAIN · $mainCount",color=if(mainCount>0)DG else DM,fontWeight=FontWeight.Bold);Text("FOLDBACK · $foldbackCount",color=if(foldbackCount>0)DG else DM,fontWeight=FontWeight.Bold);Text("TOTAL · $totalCount",fontWeight=FontWeight.Black)};Text("Counts active presentation connections, not merely discovered devices.",fontSize=11.sp,color=DM)}}
 Card{Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("GOOGLE CAST",fontWeight=FontWeight.Black);Text(if(castDevice==null)castMessage else "● $castDevice connected",color=if(castDevice==null)DM else DG);RouteSelector(OutputTransport.CAST){routeRevision++};Button({castSearching=true;castMessage="Searching for Cast TVs…"},Modifier.fillMaxWidth(),enabled=!castSearching){Text(if(castSearching)"SEARCHING…" else if(castDevice==null)"FIND CAST TVs" else "FIND / CHANGE CAST TV")};if(castSearching)LinearProgressIndicator(Modifier.fillMaxWidth());castRoutes.forEach{route->Surface(Modifier.fillMaxWidth(),color=DS,shape=RoundedCornerShape(14.dp)){Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(route.name,fontWeight=FontWeight.Bold);Text(route.description.orEmpty(),fontSize=11.sp,color=DM)};Button({connectCastRoute(route)}){Text("CONNECT")}}}};if(castRoutes.isNotEmpty())Text("Tap CONNECT to start a Cast session with that TV.",fontSize=11.sp,color=DM);Text("Cast can carry either Main or Foldback. One active Cast session is controlled at a time.",fontSize=11.sp,color=DM)}}
 Card{Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("FOLDBACK",fontWeight=FontWeight.Black);Text("Private stage feed controls: clock, timer, current/next scripture and sliding alerts.",fontSize=12.sp,color=DM);OutlinedButton({foldbackControls=!foldbackControls},Modifier.fillMaxWidth()){Text(if(foldbackControls)"HIDE FOLDBACK CONTROLS" else "FOLDBACK CONTROLS")}}};if(foldbackControls)FoldbackControlsPanel()
 Card{Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("SMART TV / DLNA",fontWeight=FontWeight.Black);Text(smartMessage,color=if(smartTvs.isEmpty())DM else DG);Button({scanSmartTvs()},Modifier.fillMaxWidth(),enabled=!smartScanning){Text(if(smartScanning)"SEARCHING…" else "FIND SMART TVs")};if(smartScanning)LinearProgressIndicator(Modifier.fillMaxWidth());smartTvs.forEach{(tv,name)->Surface(Modifier.fillMaxWidth(),color=DS,shape=RoundedCornerShape(14.dp)){Column(Modifier.padding(12.dp)){Text(name,fontWeight=FontWeight.Bold);Text("${tv.address} · DLNA MediaRenderer",fontSize=11.sp,color=DM)}}};if(smartTvs.isNotEmpty())Text("Discovered TVs are not counted as connected until a presentation session is actually active.",fontSize=11.sp,color=DM)}}
 Card{Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("BROWSER DISPLAYS",fontWeight=FontWeight.Black);Text("One receiver starts both browser outputs. Open either or both addresses on devices connected to the same network.",fontSize=12.sp,color=DM);if(!browserRunning)Button({browserRunning=browser.start()!=null},Modifier.fillMaxWidth()){Text("START BROWSER RECEIVER")}else{Text("● Receiver active",color=DG);Surface(Modifier.fillMaxWidth(),color=DS,shape=RoundedCornerShape(14.dp)){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text("MAIN / CONGREGATION · $mainBrowserClients connected",fontWeight=FontWeight.Black);Text(browser.mainAddress().orEmpty(),fontSize=18.sp,fontWeight=FontWeight.Bold);Text("Audience slides and public service countdown",fontSize=11.sp,color=DM)}};Surface(Modifier.fillMaxWidth(),color=DS,shape=RoundedCornerShape(14.dp)){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text("FOLDBACK / STAGE · $foldbackBrowserClients connected",fontWeight=FontWeight.Black);Text(browser.foldbackAddress().orEmpty(),fontSize=18.sp,fontWeight=FontWeight.Bold);Text("Private current/next scripture, stage timer, clock and alerts",fontSize=11.sp,color=DM)}};Text("$browserClients browser display${if(browserClients==1)"" else "s"} connected",color=if(browserClients>0)DG else DM,fontWeight=FontWeight.Bold);OutlinedButton({browser.stop();browserRunning=false;browserClients=0;mainBrowserClients=0;foldbackBrowserClients=0},Modifier.fillMaxWidth()){Text("STOP BOTH BROWSER OUTPUTS")}}}}
 Card{Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("HDMI / EXTERNAL DISPLAY",fontWeight=FontWeight.Black);Text(if(wiredActive)"● ${wired.activeDisplayName()?:"External display"} presenting" else "No active wired presentation",color=if(wiredActive)DG else DM);RouteSelector(OutputTransport.WIRED){wired.render(null,false);routeRevision++};val displays=wired.available();if(displays.isEmpty())Text("No wired display detected",color=DM)else displays.forEach{d->Button({if(wired.show(d.id))wiredActive=true},Modifier.fillMaxWidth()){Text("USE ${d.name}")}}}}
 TextButton({diagnostics=!diagnostics}){Text(if(diagnostics)"HIDE NETWORK DIAGNOSTICS" else "NETWORK DIAGNOSTICS")};if(diagnostics)Surface(Modifier.fillMaxWidth(),color=DS,shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Nearby network devices",fontWeight=FontWeight.Bold);OutlinedButton({scan()},Modifier.fillMaxWidth(),enabled=!scanning){Text(if(scanning)"SEARCHING…" else "SCAN LOCAL NETWORK")};if(scanning)LinearProgressIndicator(Modifier.fillMaxWidth());devices.forEach{d->Text("${d.name} · ${d.protocol} · ${d.host}",fontSize=12.sp,color=DM)};if(!scanning&&devices.isEmpty())Text("No devices found",fontSize=12.sp,color=DM);Text("Network discovery does not mean a presentation connection is active.",fontSize=11.sp,color=DM)}}
}
