package com.kingzulu.biblepresentation

import android.content.Context
import org.json.JSONObject
import java.io.File

data class Verse(val reference: BibleReference,val text:String,val translation:String)
data class ScriptureMatch(val verse:Verse,val score:Double)
data class InstalledBible(val id:String,val name:String,val abbreviation:String,val source:String,val builtIn:Boolean=false)
private data class IndexedVerse(val verse:Verse,val normalized:String,val words:Set<String>)

object OfflineBibleRepository{
 private var appContext:Context?=null;private val bibleCache=mutableMapOf<String,JSONObject>();private val indexCache=mutableMapOf<String,List<IndexedVerse>>();private var selected="KJV"
 fun initialize(context:Context){appContext=context.applicationContext;val saved=context.getSharedPreferences("king_zulu_bibles",Context.MODE_PRIVATE).getString("selected","KJV")?:"KJV";selected=if(saved.equals("KJV",true)||installedBibles().any{it.abbreviation.equals(saved,true)})saved.uppercase() else "KJV";if(!selected.equals(saved,true))persistSelection(selected)}
 fun selectedTranslation()=selected
 fun selectTranslation(abbreviation:String):Boolean{val key=abbreviation.uppercase();if(installedBibles().none{it.abbreviation.equals(key,true)}||data(key)==null)return false;selected=key;persistSelection(key);return true}
 private fun persistSelection(value:String){appContext?.getSharedPreferences("king_zulu_bibles",Context.MODE_PRIVATE)?.edit()?.putString("selected",value)?.apply()}
 fun installedBibles():List<InstalledBible>{val out=mutableListOf(InstalledBible("kjv","King James Version","KJV","Bundled",true));val dir=moduleDir()?:return out;dir.listFiles{f->f.isFile&&f.extension.equals("json",true)}?.forEach{f->readModule(f)?.let{j->val meta=j.optJSONObject("meta");val abbr=(meta?.optString("abbreviation")?.takeIf{it.isNotBlank()}?:f.nameWithoutExtension).uppercase();if(abbr!="KJV")out+=InstalledBible(meta?.optString("id")?.takeIf{it.isNotBlank()}?:abbr.lowercase(),meta?.optString("name")?.takeIf{it.isNotBlank()}?:abbr,abbr,meta?.optString("source")?.takeIf{it.isNotBlank()}?:"Installed")}};return out.sortedBy{it.name}}
 fun isInstalled(abbreviation:String)=installedBibles().any{it.abbreviation.equals(abbreviation,true)};fun moduleDirectory():File?=moduleDir();fun refreshModules(){bibleCache.keys.filter{it!="KJV"}.forEach{bibleCache.remove(it)};indexCache.clear();if(selected!="KJV"&&data(selected)==null){selected="KJV";persistSelection("KJV")}}
 private fun moduleDir():File?=appContext?.let{File(it.filesDir,"bibles").apply{mkdirs()}};private fun readModule(file:File)=runCatching{JSONObject(file.readText())}.getOrNull()
 private fun data(translation:String):JSONObject?{val key=translation.uppercase();bibleCache[key]?.let{return it};val c=appContext?:return null;val loaded=if(key=="KJV")runCatching{JSONObject(c.assets.open("bibles/kjv.json").bufferedReader().use{it.readText()})}.getOrNull() else moduleDir()?.listFiles()?.firstOrNull{it.isFile&&it.extension.equals("json",true)&&it.nameWithoutExtension.equals(key,true)}?.let(::readModule);return loaded?.also{bibleCache[key]=it}}
 private fun normalizeBookName(v:String)=v.lowercase().replace(Regex("[^a-z0-9]"),"").replace("psalm","psalms");private fun normalizeText(v:String)=v.lowercase().replace(Regex("[^a-z0-9 ]")," ").replace(Regex("\\s+")," ").trim()
 fun get(r:BibleReference,translation:String=selected):Verse?{if(r.verseStart==null)return null;val key=translation.uppercase();val books=data(key)?.optJSONArray("books")?:return null;val wanted=normalizeBookName(r.book);var book:JSONObject?=null;for(i in 0 until books.length()){val c=books.optJSONObject(i)?:continue;if(normalizeBookName(c.optString("englishName"))==wanted||normalizeBookName(c.optString("book"))==wanted){book=c;break}};val chapters=book?.optJSONArray("chapters")?:return null;val chapter=(0 until chapters.length()).mapNotNull{chapters.optJSONObject(it)}.firstOrNull{it.optInt("chapter")==r.chapter}?:return null;val verses=chapter.optJSONArray("verses")?:return null;val start=r.verseStart;val end=r.verseEnd?:start;val texts=mutableListOf<String>();for(n in start..end){val v=(0 until verses.length()).mapNotNull{verses.optJSONObject(it)}.firstOrNull{it.optInt("number",it.optInt("verse"))==n}?:return null;texts+=v.optString("text").trim()};return Verse(r,texts.joinToString(" "),key)}
 fun chapter(book:String,chapter:Int,translation:String=selected):List<Verse>{val books=data(translation)?.optJSONArray("books")?:return emptyList();val wanted=normalizeBookName(book);val b=(0 until books.length()).mapNotNull{books.optJSONObject(it)}.firstOrNull{normalizeBookName(it.optString("englishName"))==wanted||normalizeBookName(it.optString("book"))==wanted}?:return emptyList();val c=b.optJSONArray("chapters")?.let{a->(0 until a.length()).mapNotNull{a.optJSONObject(it)}.firstOrNull{it.optInt("chapter")==chapter}}?:return emptyList();val vs=c.optJSONArray("verses")?:return emptyList();val name=b.optString("englishName",book);return (0 until vs.length()).mapNotNull{i->val v=vs.optJSONObject(i)?:return@mapNotNull null;val n=v.optInt("number",v.optInt("verse"));val t=v.optString("text").trim();if(n<1||t.isBlank())null else Verse(BibleReference(name,chapter,n),t,translation.uppercase())}}
 private fun index(translation:String):List<IndexedVerse>{val key=translation.uppercase();indexCache[key]?.let{return it};val out=ArrayList<IndexedVerse>();val books=data(key)?.optJSONArray("books")?:return emptyList();for(bi in 0 until books.length()){val b=books.optJSONObject(bi)?:continue;val name=b.optString("englishName");val chapters=b.optJSONArray("chapters")?:continue;for(ci in 0 until chapters.length()){val c=chapters.optJSONObject(ci)?:continue;val cn=c.optInt("chapter");val verses=c.optJSONArray("verses")?:continue;for(vi in 0 until verses.length()){val v=verses.optJSONObject(vi)?:continue;val text=v.optString("text").trim();if(text.isBlank())continue;val verse=Verse(BibleReference(name,cn,v.optInt("number",v.optInt("verse"))),text,key);val n=normalizeText(text);out+=IndexedVerse(verse,n,n.split(" ").toSet())}}};return out.also{indexCache[key]=it}}
 private fun queryWords(spoken:String):List<String>{var cleaned=normalizeText(spoken);listOf("please help me find this reference where it says","help me find the reference where it says","find the reference where it says","where does the bible say","where does scripture say","the bible says","scripture says","where it says","it says").forEach{p->if(cleaned.contains(p)){cleaned=cleaned.substringAfter(p).trim();return@forEach}};val filler=setOf("a","an","and","but","or","please","media","help","find","bible","scripture","verse","reference");return cleaned.split(" ").filter{it.length>1&&!filler.contains(it)}}
 fun searchQuoteMatches(spoken:String,limit:Int=5,translation:String=selected):List<ScriptureMatch>{val q=queryWords(spoken);if(q.size<2)return emptyList();val phrase=q.joinToString(" ");return index(translation).mapNotNull{iv->val hits=q.count{it in iv.words};if(hits<2)return@mapNotNull null;val longest=(q.size downTo 2).firstOrNull{n->q.windowed(n).any{iv.normalized.contains(it.joinToString(" "))}}?:0;val orderedPairs=q.windowed(2).count{iv.normalized.contains(it.joinToString(" "))};var score=hits.toDouble()/q.size+orderedPairs*.12+longest*longest*.08;if(iv.normalized.contains(phrase))score+=3.0;if(longest>=4)score+=1.2;if(score<.42)null else ScriptureMatch(iv.verse,score)}.sortedByDescending{it.score}.take(limit)}
 fun searchQuote(spoken:String,translation:String=selected)=searchQuoteMatches(spoken,1,translation).firstOrNull()?.takeIf{it.score>=.62}?.verse
}
