package com.kingzulu.biblepresentation

object SpokenBibleReferenceParser {
 private val numberWords=mapOf("one" to 1,"two" to 2,"three" to 3,"four" to 4,"five" to 5,"six" to 6,"seven" to 7,"eight" to 8,"nine" to 9,"ten" to 10,"eleven" to 11,"twelve" to 12,"thirteen" to 13,"fourteen" to 14,"fifteen" to 15,"sixteen" to 16,"seventeen" to 17,"eighteen" to 18,"nineteen" to 19,"twenty" to 20,"thirty" to 30,"forty" to 40,"fifty" to 50,"sixty" to 60,"seventy" to 70,"eighty" to 80,"ninety" to 90)
 private val ordinalWords=mapOf("first" to 1,"second" to 2,"third" to 3,"fourth" to 4,"fifth" to 5,"sixth" to 6,"seventh" to 7,"eighth" to 8,"ninth" to 9,"tenth" to 10,"eleventh" to 11,"twelfth" to 12,"thirteenth" to 13,"fourteenth" to 14,"fifteenth" to 15,"sixteenth" to 16,"seventeenth" to 17,"eighteenth" to 18,"nineteenth" to 19,"twentieth" to 20,"thirtieth" to 30,"fortieth" to 40,"fiftieth" to 50,"sixtieth" to 60,"seventieth" to 70,"eightieth" to 80,"ninetieth" to 90)
 private val canonical=listOf("song of solomon","1 thessalonians","2 thessalonians","1 corinthians","2 corinthians","1 chronicles","2 chronicles","1 samuel","2 samuel","1 kings","2 kings","1 timothy","2 timothy","1 peter","2 peter","1 john","2 john","3 john","genesis","exodus","leviticus","numbers","deuteronomy","joshua","judges","ruth","ezra","nehemiah","esther","job","psalms","proverbs","ecclesiastes","isaiah","jeremiah","lamentations","ezekiel","daniel","hosea","joel","amos","obadiah","jonah","micah","nahum","habakkuk","zephaniah","haggai","zechariah","malachi","matthew","mark","luke","john","acts","romans","galatians","ephesians","philippians","colossians","titus","philemon","hebrews","james","jude","revelation")
 private val aliases=mapOf(
  "psalm" to "psalms","song of songs" to "song of solomon","songs of solomon" to "song of solomon","canticles" to "song of solomon",
  "jn" to "john","jhn" to "john","rom" to "romans","rev" to "revelation","revelations" to "revelation","heb" to "hebrews","matt" to "matthew","mt" to "matthew","mk" to "mark","lk" to "luke","acts of the apostles" to "acts",
  "first samuel" to "1 samuel","second samuel" to "2 samuel","first kings" to "1 kings","second kings" to "2 kings","first chronicles" to "1 chronicles","second chronicles" to "2 chronicles","first corinthians" to "1 corinthians","second corinthians" to "2 corinthians","first thessalonians" to "1 thessalonians","second thessalonians" to "2 thessalonians","first timothy" to "1 timothy","second timothy" to "2 timothy","first peter" to "1 peter","second peter" to "2 peter","first john" to "1 john","second john" to "2 john","third john" to "3 john",
  "one samuel" to "1 samuel","two samuel" to "2 samuel","one timothy" to "1 timothy","two timothy" to "2 timothy","one john" to "1 john","two john" to "2 john","three john" to "3 john"
 )
 private fun spokenNumber(tokens:List<String>):Int?{if(tokens.isEmpty())return null;tokens.firstOrNull()?.toIntOrNull()?.let{return it};var total=0;var found=false;tokens.forEach{t->val v=numberWords[t]?:ordinalWords[t];if(v!=null){total+=v;found=true}};return if(found)total else null}
 private fun normalize(raw:String):String{var s=raw.lowercase().replace(Regex("[^a-z0-9: -]")," ").replace(Regex("\\s+")," ").trim();listOf("the book of","book of","the book","book").forEach{s=s.replace(it," ")};aliases.entries.sortedByDescending{it.key.length}.forEach{(a,b)->s=s.replace(Regex("\\b${Regex.escape(a)}\\b"),b)};return s.replace(Regex("\\s+")," ").trim()}
 fun parse(transcript:String):BibleReference?{val clean=normalize(transcript);for(book in canonical.sortedByDescending{it.length}){for(m in Regex("\\b${Regex.escape(book)}\\b").findAll(clean)){parseFromBook(clean.substring(m.range.first).trim())?.let{return it}}};val words=clean.split(" ");for(start in words.indices){for(len in 2..minOf(12,words.size-start)){BibleReferenceParser.parse(words.drop(start).take(len).joinToString(" "))?.let{return it}}};return null}
 private fun parseFromBook(text:String):BibleReference?{
  BibleReferenceParser.parse(text)?.let{return it}
  val tokens=text.split(" ");val chapterIndex=tokens.indexOfFirst{it=="chapter"};val verseIndex=tokens.indexOfFirst{it=="verse"||it=="verses"}
  if(chapterIndex>0&&verseIndex>chapterIndex){val book=tokens.subList(0,chapterIndex).joinToString(" ");val chapter=spokenNumber(tokens.subList(chapterIndex+1,verseIndex).filterNot{it in setOf("the","and")})?:return null;val after=tokens.drop(verseIndex+1);val sep=after.indexOfFirst{it=="to"||it=="through"};val firstTokens=if(sep>=0)after.take(sep)else after.takeWhile{it !in setOf("and","then","where","which","says","reads")};val verse=spokenNumber(firstTokens.take(4))?:return null;val end=if(sep>=0)spokenNumber(after.drop(sep+1).take(4))else null;return BibleReferenceParser.parse("$book $chapter:$verse${end?.let{"-$it"}?:""}")}
  // Handles recognizer output such as “John eleven sixteen through thirty four”.
  for(book in canonical.sortedByDescending{it.length})if(text.startsWith(book)){val tail=text.removePrefix(book).trim().replace(":"," ").replace("-"," through ").split(" ").filter{it.isNotBlank()};if(tail.isNotEmpty()){val through=tail.indexOf("through").takeIf{it>=0}?:tail.indexOf("to").takeIf{it>=0};for(split in 1 until tail.size){val ch=spokenNumber(tail.take(split))?:continue;val verseTokens=if(through!=null&&through>=split)tail.subList(split,through)else tail.drop(split);val v=spokenNumber(verseTokens.take(3))?:continue;val end=through?.let{spokenNumber(tail.drop(it+1).take(3))};BibleReferenceParser.parse("$book $ch:$v${end?.let{"-$it"}?:""}")?.let{return it}}}}
  return null
 }
}
